language: r
cache: packages
r: 3.4.4
pandoc_version: 1.19.2.1
repos:
  CRAN: https://cran.rstudio.com
if: tag IS blank AND branch = master
notifications:
  email:
    on_failure: always
    on_success: never
script:
- make simulations.pdf
- make simulations.md
- make simulations.html
